### ISSUE TITLE
Temperate Rainforest missing leaves

### ISSUE THREAD

**Issue by Syndaryl** [Prospector/Traverse#40]
![image](https://user-images.githubusercontent.com/8820565/53514229-41ccf500-3a95-11e9-9b67-6cf4bb9ce796.png)

Thicket and Forested Hills are also leaf-less, a few others might also be afflicted.

They all seem to be the same basic tree type, so fixing it might fix the entire problem.

**Comment by Prospector** [comment]
Those trees are not from my mod, so it has nothing to do with me.

**Comment by Syndaryl** [comment]
Sorry about that!
