### ISSUE TITLE
lang files not working in resourcepack

### ISSUE THREAD

**Issue by IronPiston** [Prospector/Traverse#44]
Trying to use the en_US.lang inside .../assets/traverse/lang for my resourcepack doesn't change the names of any block of the game. This also extends to other languages.

**Comment by Prospector** [comment]
It should be en_us.lang

**Comment by IronPiston** [comment]
Ah ok. I had extracted the assets folder from the .jar file, and was trying to use that. en_us.lang works correctly, thanks!
